import Head from "next/head";
import Image from "next/image";
import { BiMicrophone } from "react-icons/bi";
import { FaTelegramPlane } from "react-icons/fa";
import { BsTwitter } from "react-icons/bs";

export default function Home() {
  return (
    <div className='overflow-hidden'>
      <Head>
        <title>AI ROSWELL</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.svg' />
      </Head>
      <section className='h-screen relative flex flex-col items-center overflow-hidden w-full'>
        <Image
          src='/robot-lg.webp'
          fill
          className='object-contain z-[10] hidden lg:flex '
        />

        <h1 className='text-purple press-font text-[20px] text-center  my-[80px] lg:text-[60px] max-w-[1000px] z-20 '>
          Welcome to the AI ROSWELL{" "}
        </h1>
        <input
          type='text'
          placeholder='Ask me any question... '
          className='bg-purple-black w-[320px] h-[49px] rounded-full p-4 text-white z-20 lg:w-[700px] lg:mt-[300px] outline-none lg:h-[60px] '
        />
        <button className='rounded-full w-[70px] h-[70px] bg-violet-700/25 flex items-center justify-center  my-[30px] z-20'>
          <BiMicrophone className='text-white text-[30px]  ' />
        </button>
        <Image
          src={"/robot-sm.webp"}
          width={300}
          height={300}
          className='lg:hidden'
        />
      </section>

      {/* second section */}

      <section className=' pt-[100px] xl:px-[194px] '>
        <div className='lg:flex '>
          <div className='flex flex-col items-center lg:justify-center lg:items-start  '>
            <p className='text-white/60 font-bold px-[42px] text-[20px] max-w-[656px]'>
              Meet Roswell, the intelligent robot designed to enhance your
              experience in a digital ecosystem. With advanced AI, you can swap,
              farm, and stake coins for rewards, while playing against Roswell
              for incentives. Roswell&apos;s personalized interface and constant
              learning make it easy to stay ahead of the game. Join now and
              discover a new world of possibilities with Roswell as your guide.
            </p>

            <button className='animate-pulse text-purple font-bold flex items-center bg-purple-black mx-auto lg:mx-[42px] my-10 justify-center w-[155px] h-[55px] rounded-full'>
              Join The Quest
            </button>
          </div>
          <div className='w-[334px]  h-[356px]  xl:h-[443px] xl:w-[443px] relative mx-auto  '>
            <Image src='/drone.webp' className='object-contain' fill />
          </div>
        </div>
      </section>

      {/* card section */}
      {/* <section className=''>
        <div className='border-2 w-[800px] h-[200px] relative mx-auto '>
          {[...Array(4)].map((_, i) => (
            <div
              className={`w-[100px]  h-[200px] rounded-lg  absolute ${`left-${
                i + 1
              }00px`} `}
            ></div>
          ))}
        </div>
      </section> */}

      <footer className='flex flex-col mt-[50px]  '>
        <div className=' flex flex-col items-center'>
          <h2 className='text-white/60 text-center font-bold text-xl px-5 md:text-[30px] xl:text-[40px] '>
            Roswell Ai provides safe & low-cost trading experience
          </h2>
          <div className='flex flex-col items-center  md:space-x-10  md:flex-row  lg:mt-[91px]'>
            <button className='animate-pulse font-bold text-purple flex items-center bg-purple-black mx-auto  my-10 justify-center w-[155px] h-[55px] rounded-full'>
              LEARN NOW
            </button>
            <p className='text-white font-bold text-xl'>Learn</p>
          </div>
        </div>

        <div className='flex flex-col lg:flex-row w-full lg:justify-between lg:px-[30px]  items-center mt-[50px] '>
          {/*  */}
          <div className='text-purple flex text-[40px] space-x-10'>
            <FaTelegramPlane />
            <BsTwitter />
          </div>

          {/*  */}
          <div className='flex text-purple lg:ml-14  justify-center items-center press-font space-x-[20px] '>
            <Image src='logo.svg' width={90} height={117} />
            <p className='text-purple text-[20px]'>ROSWELL</p>
          </div>
          {/*  */}
          <p className='text-white font-bold press-font my-10'>
            contact@figmafiles.com
          </p>
        </div>
      </footer>
    </div>
  );
}
